# @package dataset
_target_: src.configs.dataset.CodeSelectionConfig

# Test case settings
include_test_cases: true
use_incorrect_tests: false

# Train/validation split
train_ratio: 0.8
random_seed: ${dataset_seed}
