# @package dataset
_target_: src.configs.dataset.RLRewardHackingConfig

hint_type: "SimpleOverwriteTests"
data_path: "data/rl_rewardhacking/half1_simple.jsonl"
difficulties: null
train_ratio: 0.8
random_seed: ${dataset_seed}
